#167765388 Users should receive JWT on registration
andela/phoenix-bn-backend pull request #28
Opened 2019-09-05 07:35 UTC by victor-nach

## What does this PR do?
- Users should receive JWT on registration

## Description of Task to be completed?
- install jwt
- create utility functions for creating JWT
- add token to response on succesful creation of a user

## How should this be manually tested?
- Add SECRET key to you r environment variables
- Run npm run test to test the branch
- send a post request containing the relevant user fields to POST /api/v1/users
- confirm that a token is part of the returned response

## What are the relevant pivotal tracker stories?
- #167765388

## Implementation Plan Document

2019-09-05 20:48 UTC, debelistic approved these changes
Works fine, tests are passing, great job. Update the route specification in your PR description, I had to look into the code to find out

2019-09-05 21:01 UTC, debelistic requested changes

2019-09-05 21:01 UTC, debelistic commented on src/controllers/UserController.js
> +      const token = Utils.generateToken({ id: userData.id, isAdmin: userData.isAdmin });
I don't really understand what's going on here. It seems you are passing the id and admin status as payload:
1. I think it should be the username or email
2. You authenticated the user id from the request object which is probably undefined since the user wouldn't be sending an id with their request. The properties to be authenticated should be coming from the db not the user request. That would imply an unsaved user can be authenticated

2019-09-05 21:51 UTC, victor-nach commented
> Works fine, tests are passing, great job. Update the route specification in your PR description, I had to look into the code to find out

ok, sure

2019-09-05 21:55 UTC, victor-nach commented on src/controllers/UserController.js
> +      const token = Utils.generateToken({ id: userData.id, isAdmin: userData.isAdmin });
- yh, that's true, I'll use the id from the db.
- The id is the primary key in the table, that's why I'm using it for the payload

2019-09-05 22:14 UTC, debelistic approved these changes

2019-09-06 07:49 UTC, okobaba1 reviewed
Maybe you might have created  a file specifically instead of using index

2019-09-06 10:44 UTC, anneKay commented on src/controllers/UserController.js
> +        data: { token, ...data },
Add the returned token in the header

2019-09-06 10:55 UTC, anneKay commented
We should also have a method which decodes the JWT, don't you think so?

2019-09-06 11:47 UTC, victor-nach commented
> We should also have a method which decodes the JWT, don't you think so?
- That method is another PR, and the login functionality is a blocker to that PR.

2019-09-06 13:42 UTC, anneKay approved these changes

2019-09-06 13:43 UTC, merged