#168301296 Secure admin create user route with jwt
andela/phoenix-bn-backend pull request #29
Opened 2019-09-05 09:21 UTC by victor-nach

## What does this PR do?
- Allows only admin to be able to create a new user

## Description of Task to be completed?
- write jwt decode methods
- create middlewares to decode token
- add auth middlewares to admin routes

## How should this be manually tested?
- clone this branch
- Run npm run test to test the branch
- login with an admin to receive a token
- send a post request containing the relevant user fields to POST /api/v1/users with token attached

## What are the relevant pivotal tracker stories?
- #168301296

## Implementation Plan Document

2019-09-05 20:28 UTC, debelistic requested changes
Test are failing at the moment. Seems you need to authenticate the admin user before they can register, the routes are returning 401

2019-09-05 21:50 UTC, victor-nach commented
- yes this branch is dependent on the login feature being completed

2019-09-12 09:00 UTC, victor-nach commented
The login feature has now been merged, you can test this out again

2019-09-12 09:04 UTC, voke1 commented on src/tests/userSpec.js
> +      console.log(res.headers.authorization)
Please, remove all console.log

2019-09-12 09:36 UTC, victor-nach commented on src/tests/userSpec.js
> +      console.log(res.headers.authorization)
done, thanks

2019-09-12 09:49 UTC, debelistic approved these changes

2019-09-12 11:21 UTC, voke1 requested changes

2019-09-12 11:21 UTC, voke1 commented on src/database/seeders/20190906184341-Users.js
> +        email: 'wetraveluser1@gmail.com',
why change the email. `wetravel.user1@gmail` is registered with linkedin to sign in successfully with linkedin. I'll suggest you use this instead `chidimma@gmail.com` for test.

2019-09-12 11:31 UTC, victor-nach commented on src/database/seeders/20190906184341-Users.js
> +        email: 'wetraveluser1@gmail.com',
Hmm, okay, there were some issues retreiving that email with sequelize, so I wasn't able to use it to test, that's why I removed the '. '

2019-09-12 11:33 UTC, anneKay commented on src/controllers/UserController.js
> +      const token = Utils.generateToken({ id, isAdmin, email });
Why did you add user's email here? and please remove the isAdmin since we are oo longer working with that.

2019-09-12 11:37 UTC, victor-nach commented on src/controllers/UserController.js
> +      const token = Utils.generateToken({ id, isAdmin, email });
Ugo's branch added an email to the token he generated for sign in, so to keep it consistent I also added an email to the sign up.

2019-09-12 11:58 UTC, voke1 commented on src/database/seeders/20190906184341-Users.js
> +        email: 'wetraveluser1@gmail.com',
> Hmm, okay, there were some issues retreiving that email with sequelize, so I wasn't able to use it to test, that's why I removed the '. '

Yes. I noticed. This is because the email validation actually trims the '.' off. So, instead of having wetravel.user1@gmail.com you have wetraveluser1@gmail.com.

2019-09-12 12:07 UTC, voke1 commented on src/controllers/UserController.js
> +      const token = Utils.generateToken({ id, isAdmin, email });
I think its best we add the email here too. So we have a single Service method to check for users, instead of having a `getUserById` method when a user registers and another `getUserByEmail` when a user login.

2019-09-12 12:11 UTC, voke1 commented on src/tests/routes/userSpec.js
> +      .set('Authorization', token)
I don't think this `.set('Authorization', token)` is necessary since we are not using token on this route, admin adds a user

2019-09-12 12:33 UTC, victor-nach commented on src/tests/routes/userSpec.js
> +      .set('Authorization', token)
no we are using token on this route, that's the main point of this PR, to secure the create user route. for now since roles haven't been implemented, we just check for token

2019-09-12 12:34 UTC, victor-nach commented on src/database/seeders/20190906184341-Users.js
> +        email: 'wetraveluser1@gmail.com',
so I should leave it like this?, is it possible for you to update the one registered with linkedn

2019-09-12 13:44 UTC, voke1 commented on src/tests/routes/userSpec.js
> +      .set('Authorization', token)
oh okay.

2019-09-12 13:54 UTC, voke1 approved these changes

2019-09-12 14:23 UTC, merged