Configure Eslint
andela/phoenix-bn-backend pull request #3
Opened 2019-08-14 23:20 UTC by okobaba1

#### What does this PR do?
This PR configures eslint 
#### Description of Task to be completed?
Using npm, Install eslint, eslint-config-airbnb-base, and eslint-plugin-import as DevDependencies
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#167765379](https://www.pivotaltracker.com/story/show/167765379)

2019-08-15 17:19 UTC, debelistic requested changes
Great job,
1. There is no need to add the extension name, since you named it .eslintrc
2. Since the rules you added are defaults for airbnb style guide, I feel we don't need to add them. Those rules are extended by default.
3. You could just use an object since the file would be in root folder, it will be available globally in all files.

Try effect those and inform Anna

2019-08-16 08:05 UTC, anneKay commented on .eslintrc
> +}
Add newline

2019-08-16 08:24 UTC, debelistic approved these changes

2019-08-16 08:59 UTC, okobaba1 commented on .eslintrc
> +}
Done @anneKay

2019-08-16 12:59 UTC, merged